replicaCount: 1

image:
  repository: 906328874067.dkr.ecr.us-east-2.amazonaws.com/ai-api
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
