apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "ai-api.fullname" . } }
  labels:
    app: { { include "ai-api.name" . } }
    version: { { .Values.image.tag } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { include "ai-api.name" . } }
      version: { { .Values.image.tag } }
  template:
    metadata:
      labels:
        app: { { include "ai-api.name" . } }
        version: { { .Values.image.tag } }
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: 80
