apiVersion: apps/v1
kind: Deployment
metadata:
  name:
    {
      {
        .Values.deploymentName | default (printf "%s-%s" .Chart.Name .Values.image.tag),
      },
    }
  labels:
    app: { { .Values.nameOverride | default .Chart.Name } }
    version: { { .Values.image.tag } }
spec:
  replicas: { { .Values.replicaCount | default 1 } }
  selector:
    matchLabels:
      app: { { .Values.nameOverride | default .Chart.Name } }
      version: { { .Values.image.tag } }
  template:
    metadata:
      labels:
        app: { { .Values.nameOverride | default .Chart.Name } }
        version: { { .Values.image.tag } }
    spec:
      containers:
        - name: { { .Values.nameOverride | default .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy:
            { { .Values.image.pullPolicy | default "IfNotPresent" } }
          ports:
            - containerPort: 80
