apiVersion: v1
kind: Service
metadata:
  name: { { include "ai-api.fullname" . } }
spec:
  type: ClusterIP
  selector:
    app: { { include "ai-api.name" . } }
  ports:
    - port: 80
      targetPort: 5050
      protocol: TCP
      name: http
