apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "ai-api.name" . }}-vs-{{ .Values.image.tag }}
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/{{ include "ai-api.name" . }}-gw-{{ .Values.image.tag }}
  http:
    - route:
        - destination:
            host: {{ include "ai-api.name" . }}
            subset: v1
          weight: 90
        - destination:
            host: {{ include "ai-api.name" . }}
            subset: v2
          weight: 10
