apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ai-api-vs
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/ai-api-gw
  http:
    - route:
        - destination:
            host: ai-api
            subset: v1
          weight: 90
        - destination:
            host: ai-api
            subset: v2
          weight: 10
