pipeline {
  agent any

  environment {
    AWS_REGION = 'us-east-1'
    ECR_REPO = 'your-ecr-repo-name' // no .dkr stuff
    IMAGE_TAG = "${env.BUILD_NUMBER}"
    TF_WORKING_DIR = '03-devops-capstone/infra-pipelines/eks/terraform'
  }

  stages {
    stage('Build Docker Image') {
      steps {
        script {
          docker.build("${ECR_REPO}:${IMAGE_TAG}")
        }
      }
    }

    stage('Login to ECR') {
      steps {
        withCredentials([[
          $class: 'AmazonWebServicesCredentialsBinding',
          credentialsId: 'aws-credentials'
        ]]) {
          sh '''
            aws ecr get-login-password --region $AWS_REGION | \
            docker login --username AWS --password-stdin \
            <your_account_id>.dkr.ecr.$AWS_REGION.amazonaws.com
          '''
        }
      }
    }

    stage('Push to ECR') {
      steps {
        script {
          docker.image("${ECR_REPO}:${IMAGE_TAG}")
                .push()
        }
      }
    }

    stage('Deploy to EKS via Helm') {
      steps {
        sh '''
          helm upgrade --install ai-api ./helm \
            --set image.repository=<your_account_id>.dkr.ecr.$AWS_REGION.amazonaws.com/${ECR_REPO} \
            --set image.tag=${IMAGE_TAG}
        '''
      }
    }
  }
}
