pipeline {
  agent any

  environment {
    AWS_REGION = 'us-east-1'
  }

  stages {
    stage('Terraform Init') {
      steps {
        dir('03-devops-capstone/infra-pipeline/terraform') {
          sh 'terraform init'
        }
      }
    }

    stage('Terraform Plan') {
      steps {
        dir('03-devops-capstone/infra-pipeline/terraform') {
          sh 'terraform plan -out=tfplan'
        }
      }
    }

    stage('Terraform Apply') {
      steps {
        dir('03-devops-capstone/infra-pipeline/terraform') {
          sh 'terraform apply -auto-approve tfplan'
        }
      }
    }
  }
}
