pipeline {
  agent any

  environment {
    TF_WORKING_DIR = '03-devops-capstone/infra-pipelines/vpc/terraform'
    AWS_REGION = 'us-east-1'
  }

  stages {
    stage('Terraform Init') {
      steps {
        dir("${TF_WORKING_DIR}") {
          sh 'terraform init'
        }
      }
    }

    stage('Terraform Plan') {
      steps {
        dir("${TF_WORKING_DIR}") {
          sh 'terraform plan -out=tfplan'
        }
      }
    }

    stage('Terraform Apply') {
      steps {
        dir("${TF_WORKING_DIR}") {
          input message: "Apply Terraform plan?"
          sh 'terraform apply tfplan'
        }
      }
    }
  }
}
