echo "Current Git branch: ${env.BRANCH_NAME}"
pipeline {
  agent any

  environment {
    TF_WORKING_DIR = '03-devops-capstone/infra-pipelines/vpc/terraform'
    AWS_REGION = 'us-east-1'
  }

stages {
    stage('Terraform Init') {
      steps {
        dir(env.TF_WORKING_DIR) {
          withCredentials([[
            $class: 'AmazonWebServicesCredentialsBinding',
            credentialsId: 'aws-credentials'
          ]]) {
            sh 'terraform init'
          }
        }
      }
    }

    stage('Terraform Plan') {
      steps {
        dir(env.TF_WORKING_DIR) {
          withCredentials([[
            $class: 'AmazonWebServicesCredentialsBinding',
            credentialsId: 'aws-credentials'
          ]]) {
            sh 'git branch --show-current'
            sh 'terraform plan -out=tfplan'
          }
        }
      }
    }

    stage('Terraform Apply') {
      when {
        branch 'main'
      }
      steps {
        dir(env.TF_WORKING_DIR) {
          withCredentials([[
            $class: 'AmazonWebServicesCredentialsBinding',
            credentialsId: 'aws-credentials'
          ]]) {
            sh 'git branch --show-current'
            sh 'terraform apply -auto-approve tfplan'
          }
        }
      }
    }
  }
}
