apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-mariadb
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-mariadb
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.mariadb.image }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mariadb.rootPassword | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.dbName | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.user | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mariadb.password | quote }}
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-mariadb-pvc
