apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-api-v2
spec:
  selector:
    app: {{ .Chart.Name }}-api-v2
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
