apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-mariadb
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}-mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
