apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://your.repo.url/03-devops-capstone.git
    targetRevision: HEAD
    path: ai-api/helm/ai-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
