replicaCount: 1

image:
  repository: 906328874067.dkr.ecr.us-east-2.amazonaws.com
  api:
    name: capstone-api
    v1tag: v1.0
    v2tag: v2.0
  web:
    name: capstone-web
    v1tag: v1.0
    v2tag: v2.0

service:
  type: ClusterIP
  apiPort: 8082
  webPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

mariadb:
  image: mariadb:10.5
  rootPassword: supersecure
  dbName: events
  user: eventsuser
  password: eventspass
  storageClassName: gp2

istio:
  weight:
    v1: 100
    v2: 0

grafana:
  adminPassword: "admin" # Change this or pull from a secret
  service:
    type: LoadBalancer
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: gp2
  plugins:
    - grafana-piechart-panel
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          options:
            path: /var/lib/grafana/dashboards
  dashboardsConfigMaps:
    default: grafana-dashboards
