replicaCount: 1

image:
  repository: 172.16.0.139:32000
  api:
    name: events-api
    v1tag: v1.0
    v2tag: v2.0
  web:
    name: events-website
    v1tag: v1.0
    v2tag: v2.0

service:
  type: NodePort
  apiPort: 8082
  webPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

mariadb:
  image: mariadb:10.5
  rootPassword: supersecure
  dbName: events
  user: eventsuser
  password: eventspass
