apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ai-api-destination
  namespace: default
spec:
  host: ai-api
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
