apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api-v1
  labels:
    app: {{ .Chart.Name }}-api-v1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-api-v1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-api-v1
    spec:
      containers:
      - name: {{ .Values.image.api.name }}
        image: "{{ .Values.image.repository }}/{{ .Values.image.api.name }}:{{ .Values.image.api.v1tag }}"
        ports:
        - containerPort: {{ .Values.service.apiPort }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        env:
        - name: DB_HOST
          value: "{{ .Chart.Name }}-mariadb"
        - name: DB_USER
          value: "{{ .Values.mariadb.user }}"
        - name: DB_PASSWORD
          value: "{{ .Values.mariadb.password }}"
        - name: DB_NAME
          value: "{{ .Values.mariadb.dbName }}"
