apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Chart.Name }}-destination
spec:
  host: {{ .Chart.Name }}-web
  subsets:
    - name: v1
      labels:
        app: {{ .Chart.Name }}-web
    - name: v2
      labels:
        app: {{ .Chart.Name }}-web
