apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Chart.Name }}-destination
spec:
  host: {{ .Chart.Name }}-web
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
