apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-api-v1
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}-api-v1
  ports:
    - protocol: TCP
      port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
