apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-web
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}-web
  ports:
    - protocol: TCP
      port: {{ .Values.service.webPort }}
      targetPort: {{ .Values.service.webPort }}
