apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-web
spec:
  selector:
    app: {{ .Chart.Name }}-web
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: {{ .Values.service.webPort }}
