apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}-vs
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Chart.Name }}-gateway
  http:
    - route:
        - destination:
            host: {{ .Chart.Name }}-web-v1
            port:
              number: {{ .Values.service.webPort }}
          weight: {{ .Values.istio.weight.v1 }}
        - destination:
            host: {{ .Chart.Name }}-web-v2
            port:
              number: {{ .Values.service.webPort }}
          weight: {{ .Values.istio.weight.v2 }}
